using Avalonia; using Avalonia.Controls; using Avalonia.Layout; using Avalonia.Media; using Avalonia.Platform.Storage; using Avalonia.Threading; using System.Collections.ObjectModel;
namespace StreamPAL.Linux;
public sealed class MainWindow : Window
{
    private readonly ObservableCollection<SourceInstance> _instances = []; private readonly LinuxAudioEngine _engine = new(); private readonly ProfileStore _store = new();
    private readonly ListBox _instancesList = new() { Width = 250 }, _encodersList = new() { MinHeight = 140 };
    private readonly TextBox _instanceName = new(), _source = new(), _encoderName = new(), _host = new(), _port = new(), _mount = new(), _password = new(), _metadata = new(), _log = new() { IsReadOnly = true, AcceptsReturn = true, Height = 110 };
    private readonly ComboBox _sourceType = Box("PipeWire", "JACK", "File", "Streaming URL", "Test tone"), _rate = Box(32000, 44100, 48000), _codec = Box("MP3", "AAC-LC", "AAC+ (HE-AAC)", "OGG Vorbis", "Opus"), _server = Box("Icecast 2", "SHOUTcast v2"), _bitrate = Box(32, 48, 64, 96, 128, 160, 192, 256, 320), _channel = Box("Stereo", "Solo sinistro", "Solo destro", "Mono (L+R)");
    private SourceInstance? CurrentInstance => _instancesList.SelectedItem as SourceInstance; private EncoderProfile? CurrentEncoder => _encodersList.SelectedItem as EncoderProfile; private readonly DispatcherTimer _refresh = new() { Interval = TimeSpan.FromMilliseconds(500) };
    public MainWindow()
    {
        Title = "StreamPAL"; Width = 1280; Height = 790; MinWidth = 1050; Background = Brush.Parse("#F3F6F9"); Content = Build();
        Opened += async (_, _) => { foreach (var x in await _store.LoadAsync()) _instances.Add(x); if (_instances.Count == 0) _instances.Add(new()); _instancesList.ItemsSource = _instances; _instancesList.SelectedIndex = 0; if (Environment.GetCommandLineArgs().Contains("--start-all")) foreach (var i in _instances) foreach (var e in i.Encoders) _engine.StartEncoder(i, e); };
        Closing += (_, _) => _engine.Dispose(); _instancesList.SelectionChanged += (_, _) => LoadInstance(); _encodersList.SelectionChanged += (_, _) => LoadEncoder(); _refresh.Tick += (_, _) => { _instancesList.Items.Refresh(); _encodersList.Items.Refresh(); if (CurrentEncoder is { } e) _log.Text = e.Log; }; _refresh.Start();
    }
    private Control Build()
    {
        var root = new DockPanel { Margin = new Thickness(14) }; var menu = new Menu { ItemsSource = new[] { new MenuItem { Header = "File", ItemsSource = new[] { Item("Salva configurazione", async () => await Save()), Item("Esporta configurazione…", Export), Item("Importa configurazione…", Import), Item("Avvia con Ubuntu", () => SetAutostart(false)), Item("Avvia tutto con Ubuntu", () => SetAutostart(true)), Item("Esci", Close) } }, new MenuItem { Header = "Info", ItemsSource = new[] { Item("Informazioni su StreamPAL", () => ShowInfo()) } } } }; DockPanel.SetDock(menu, Dock.Top); root.Children.Add(menu);
        var title = new TextBlock { Text = "StreamPAL  1.0.0", FontSize = 25, FontWeight = FontWeight.Bold, Foreground = Brush.Parse("#2468F2"), Margin = new Thickness(8) }; DockPanel.SetDock(title, Dock.Top); root.Children.Add(title);
        var grid = new Grid { ColumnDefinitions = new("250,12,*") }; var left = new StackPanel { Spacing = 8 }; left.Children.Add(new TextBlock { Text = "ISTANZE (MAX 64)" }); left.Children.Add(_instancesList); left.Children.Add(Row(Button("+ Istanza", AddInstance), Button("Rimuovi", RemoveInstance))); grid.Children.Add(left);
        var editor = new StackPanel { Spacing = 8 }; Grid.SetColumn(editor, 2); grid.Children.Add(editor); editor.Children.Add(Section("Sorgente condivisa", Row(Field("Nome", _instanceName), Field("Tipo", _sourceType), Field("Dispositivo, file o URL", _source), Field("Campionamento", _rate)))); editor.Children.Add(Row(Button("Applica sorgente", ApplySource), Button("+ Encoder", AddEncoder))); editor.Children.Add(_encodersList);
        var fields = new WrapPanel { Orientation = Orientation.Horizontal }; foreach (var f in new[] { Field("Nome encoder", _encoderName), Field("Codec", _codec), Field("Bitrate", _bitrate), Field("Canali", _channel), Field("Server", _server), Field("Host", _host), Field("Porta", _port), Field("Mount", _mount), Field("Password", _password), Field("Metadata", _metadata) }) fields.Children.Add(f); editor.Children.Add(Section("Encoder", fields)); editor.Children.Add(Row(Button("Salva encoder", ApplyEncoder), Button("Avvia / Ferma streaming", ToggleStreaming))); editor.Children.Add(new TextBlock { Text = "Log connessione" }); editor.Children.Add(_log); root.Children.Add(grid); return root;
    }
    private static ComboBox Box(params object[] values) => new() { ItemsSource = values, MinWidth = 140 }; private static Button Button(string text, Action action) => new() { Content = text, Command = new ActionCommand(action) }; private static MenuItem Item(string text, Action action) => new() { Header = text, Command = new ActionCommand(action) };
    private static StackPanel Row(params Control[] controls) { var p = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8 }; foreach (var c in controls) p.Children.Add(c); return p; } private static StackPanel Field(string name, Control control) { var p = new StackPanel { MinWidth = 160, Margin = new Thickness(3) }; p.Children.Add(new TextBlock { Text = name, FontSize = 11 }); p.Children.Add(control); return p; } private static Border Section(string title, Control content) { var p = new StackPanel { Spacing = 7 }; p.Children.Add(new TextBlock { Text = title, FontWeight = FontWeight.Bold }); p.Children.Add(content); return new Border { Background = Brushes.White, CornerRadius = new CornerRadius(8), Padding = new Thickness(12), Child = p }; }
    private void LoadInstance() { if (CurrentInstance is not { } i) return; _instanceName.Text = i.Name; _sourceType.SelectedItem = i.SourceType; _source.Text = i.Source; _rate.SelectedItem = i.InputSampleRate; _encodersList.ItemsSource = i.Encoders; _encodersList.SelectedIndex = i.Encoders.Count > 0 ? 0 : -1; } private void LoadEncoder() { if (CurrentEncoder is not { } e) return; _encoderName.Text = e.Name; _codec.SelectedItem = e.Codec; _bitrate.SelectedItem = e.BitrateKbps; _channel.SelectedItem = e.ChannelMode; _server.SelectedItem = e.ServerType; _host.Text = e.Host; _port.Text = e.Port.ToString(); _mount.Text = e.Mount; _password.Text = e.Password; _metadata.Text = e.Metadata; _log.Text = e.Log; }
    private void ApplySource() { if (CurrentInstance is not { } i) return; i.Name = _instanceName.Text ?? i.Name; i.SourceType = _sourceType.SelectedItem?.ToString() ?? "PipeWire"; i.Source = _source.Text ?? ""; i.InputSampleRate = (int?)_rate.SelectedItem ?? 48000; _instancesList.Items.Refresh(); } private void ApplyEncoder() { if (CurrentEncoder is not { } e) return; e.Name = _encoderName.Text ?? e.Name; e.Codec = _codec.SelectedItem?.ToString() ?? "MP3"; e.BitrateKbps = (int?)_bitrate.SelectedItem ?? 128; e.ChannelMode = _channel.SelectedItem?.ToString() ?? "Stereo"; e.ServerType = _server.SelectedItem?.ToString() ?? "Icecast 2"; e.Host = _host.Text ?? ""; e.Port = int.TryParse(_port.Text, out var p) ? p : 8000; e.Mount = _mount.Text ?? "/stream"; e.Password = _password.Text ?? ""; e.Metadata = _metadata.Text ?? ""; _encodersList.Items.Refresh(); }
    private void ToggleStreaming() { if (CurrentInstance is not { } i || CurrentEncoder is not { } e) return; ApplySource(); ApplyEncoder(); if (e.IsRunning) { _engine.StopEncoder(i, e); e.AddLog("Streaming arrestato"); } else try { _engine.StartEncoder(i, e); } catch (Exception ex) { e.AddLog(ex.Message); } } private void AddInstance() { if (_instances.Count < 64) { _instances.Add(new() { Name = $"Istanza {_instances.Count + 1}" }); _instancesList.SelectedIndex = _instances.Count - 1; } } private void RemoveInstance() { if (CurrentInstance is { } i) { _engine.Stop(i.Id); _instances.Remove(i); } } private void AddEncoder() { if (CurrentInstance is { } i) { i.Encoders.Add(new() { Name = $"Stream {i.Encoders.Count + 1}" }); _encodersList.Items.Refresh(); _encodersList.SelectedIndex = i.Encoders.Count - 1; } }
    private async Task Save() { ApplySource(); ApplyEncoder(); await _store.SaveAsync(_instances); } private async void Export() { var f = await StorageProvider.SaveFilePickerAsync(new() { SuggestedFileName = "StreamPAL-backup.streampal" }); if (f is not null) await _store.ExportAsync(f.Path.LocalPath, _instances); } private async void Import() { var f = (await StorageProvider.OpenFilePickerAsync(new() { AllowMultiple = false })).FirstOrDefault(); if (f is null) return; _instances.Clear(); foreach (var i in await _store.ImportAsync(f.Path.LocalPath)) _instances.Add(i); _instancesList.SelectedIndex = 0; }
    private void SetAutostart(bool all) { var dir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "autostart"); Directory.CreateDirectory(dir); var exe = Environment.ProcessPath ?? "/opt/streampal/StreamPAL"; File.WriteAllText(Path.Combine(dir, "streampal.desktop"), $"[Desktop Entry]\nType=Application\nName=StreamPAL\nExec={exe}{(all ? " --start-all" : "")}\nX-GNOME-Autostart-enabled=true\n"); } private void ShowInfo() { var w = new Window { Title = "StreamPAL", Width = 430, Height = 210, Content = new TextBlock { Margin = new Thickness(25), Text = "StreamPAL 1.0.0\nAll rights reserved\nwww.freewaves.it\nmax@freewaves.it", FontSize = 17 } }; w.Show(this); }
}
public sealed class ActionCommand(Action action) : System.Windows.Input.ICommand { public bool CanExecute(object? p) => true; public void Execute(object? p) => action(); public event EventHandler? CanExecuteChanged; }
