using System.Collections.ObjectModel;
using System.Collections.Concurrent;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using Microsoft.Win32;
using System.IO;
using StreamForge.Models;
using StreamForge.Services;

namespace StreamForge;
public partial class MainWindow : Window
{
    private const int MaxInstances = 64;
    private readonly ObservableCollection<SourceInstance> _instances = [];
    private readonly ProfileStore _store = new();
    private readonly AudioDeviceService _devices = new();
    private readonly AudioMeterService _audioMeters = new();
    private readonly ConcurrentDictionary<Guid, IBroadcastSession> _broadcastSessions = new();
    private readonly ConcurrentDictionary<Guid, DateTime> _reconnectAfter = new();
    private readonly ListenerMonitorService _listenerMonitor = new();
    private readonly MetadataUpdateService _metadataUpdater = new(); private readonly ConcurrentDictionary<Guid, string> _sentMetadata = new();
    private readonly AppSettingsService _settingsService = new();
    private AppSettings _settings = new();
    private readonly DispatcherTimer _meter = new() { Interval = TimeSpan.FromMilliseconds(80) };
    private readonly DispatcherTimer _trialTimer = new() { Interval = TimeSpan.FromSeconds(5) };
    private readonly TrialLicenseService _trial = new();
    private SourceInstance? _instance; private EncoderProfile? _encoder; private bool _loading; private DateTime _nextStatisticsSample = DateTime.MinValue; private DateTime _nextListenerPoll = DateTime.MinValue; private bool _listenerPollRunning; private bool _registrationOpen; private bool _expiryPromptShown;
    public MainWindow() { InitializeComponent(); Title = TrialLicenseService.IsTrialBuild ? "StreamPAL · TRIAL VERSION" : "StreamPAL"; _settings = _settingsService.Load(); StartWithWindowsMenu.IsChecked = _settings.StartWithWindows; StartAllWithWindowsMenu.IsChecked = _settings.StartAllWithWindows; InstanceList.ItemsSource = _instances; _meter.Tick += async (_, _) => await UpdateMetersAsync(); _trialTimer.Tick += (_, _) => CheckTrial(); RegistrationMenu.Visibility = TrialLicenseService.IsTrialBuild ? Visibility.Visible : Visibility.Collapsed; Loaded += async (_, _) => { foreach (var x in await _store.LoadAsync()) _instances.Add(x); if (_instances.Count == 0) _instances.Add(NewInstance(1)); InstanceList.SelectedIndex = 0; if (Environment.GetCommandLineArgs().Contains("--start-all") && !_trial.IsExpired) { foreach (var e in _instances.SelectMany(x => x.Encoders)) { e.Enabled = e.IsRunning = true; e.IsConnected = false; } foreach (var instance in _instances) { try { _audioMeters.Start(instance); } catch { } } _meter.Start(); EncoderGrid.Items.Refresh(); InstanceList.Items.Refresh(); } LocalizationService.Apply(this, _settings.Language); RefreshTrialUi(); RefreshFooter(); if (TrialLicenseService.IsTrialBuild) { _trialTimer.Start(); if (!_trial.NoticeShown && !_trial.IsRegistered) { _trial.MarkNoticeShown(); ShowRegistration(); } else if (_trial.IsExpired) { _expiryPromptShown = true; ShowRegistration(true); } } }; }
    private static SourceInstance NewInstance(int n) => new() { Name = $"Istanza {n}", Encoders = [new EncoderProfile { Name = "Stream 1" }] };
    private static string Value(ComboBox b) => (b.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? b.Text;
    private static void Select(ComboBox b, string value) { foreach (var x in b.Items.OfType<ComboBoxItem>()) if (x.Content?.ToString() == value) { b.SelectedItem = x; return; } b.Text = value; }
    private void InstanceList_SelectionChanged(object sender, SelectionChangedEventArgs e) { _instance = InstanceList.SelectedItem as SourceInstance; _loading = true; if (_instance is not null) { InstanceNameBox.Text = _instance.Name; Select(SourceTypeBox, _instance.SourceType); foreach (var item in InputRateBox.Items.OfType<ComboBoxItem>()) if (item.Tag?.ToString() == _instance.InputSampleRate.ToString()) InputRateBox.SelectedItem = item; LoadDevices(); SourceDeviceBox.Text = _instance.Source; EncoderGrid.ItemsSource = _instance.Encoders; EncoderGrid.SelectedIndex = _instance.Encoders.Count > 0 ? 0 : -1; } _loading = false; RefreshFooter(); }
    private void EncoderGrid_SelectionChanged(object sender, SelectionChangedEventArgs e) { _encoder = EncoderGrid.SelectedItem as EncoderProfile; _loading = true; EncoderEditor.IsEnabled = _encoder is not null; if (_encoder is not null) { EncoderNameBox.Text = _encoder.Name; Select(ChannelBox, _encoder.ChannelMode); Select(CodecBox, _encoder.Codec); Select(OutputModeBox, _encoder.OutputMode); Select(BitrateBox, _encoder.BitrateKbps.ToString()); Select(RateBox, _encoder.SampleRate.ToString()); Select(ServerBox, _encoder.ServerType); HostBox.Text = _encoder.Host; PortBox.Text = _encoder.Port.ToString(); MountBox.Text = _encoder.Mount; PasswordBox.Password = _encoder.Password; MetadataBox.Text = _encoder.Metadata; StationNameBox.Text = _encoder.StationName; DescriptionBox.Text = _encoder.Description; StationUrlBox.Text = _encoder.StationUrl; GenreBox.Text = _encoder.Genre; AimBox.Text = _encoder.Aim; IrcBox.Text = _encoder.Irc; IcqBox.Text = _encoder.Icq; EnabledBox.IsChecked = _encoder.Enabled; UpdateStatus(); } _loading = false; }
    private void SharedSource_Changed(object sender, EventArgs e) { if (_loading || _instance is null || !IsLoaded) return; _instance.Name = InstanceNameBox.Text; InstanceList.Items.Refresh(); }
    private void SourceType_Changed(object sender, SelectionChangedEventArgs e) { if (_loading || _instance is null || !IsLoaded) return; _instance.SourceType = Value(SourceTypeBox); LoadDevices(); InstanceList.Items.Refresh(); }
    private void SourceDevice_Changed(object sender, SelectionChangedEventArgs e) { if (_loading || _instance is null) return; _instance.Source = SourceDeviceBox.SelectedValue?.ToString() ?? SourceDeviceBox.Text; }
    private void SourceDevice_TextCommitted(object sender, System.Windows.Input.KeyboardFocusChangedEventArgs e) { if (!_loading && _instance is not null) _instance.Source = SourceDeviceBox.Text.Trim(); }
    private void InputRate_Changed(object sender, SelectionChangedEventArgs e) { if (_loading || _instance is null || InputRateBox.SelectedItem is not ComboBoxItem item) return; if (int.TryParse(item.Tag?.ToString(), out var rate)) _instance.InputSampleRate = rate; }
    private void RefreshDevices_Click(object sender, RoutedEventArgs e) => LoadDevices();
    private void LoadDevices() { var type = Value(SourceTypeBox); SourceDeviceBox.ItemsSource = _devices.Enumerate(type); SourceDeviceBox.IsEditable = true; if (type is "Test tone") SourceDeviceBox.Text = "Generatore interno"; else if (type is "File") SourceDeviceBox.Text = _instance?.Source ?? "Seleziona un file"; else if (type is "Streaming URL") SourceDeviceBox.Text = _instance?.Source ?? "https://"; }
    private void EncoderField_Changed(object sender, EventArgs e) { if (_loading || _encoder is null || !IsLoaded) return; _encoder.Name = EncoderNameBox.Text; _encoder.ChannelMode = Value(ChannelBox); _encoder.Codec = Value(CodecBox); _encoder.OutputMode = Value(OutputModeBox); if (int.TryParse(Value(BitrateBox), out var b)) _encoder.BitrateKbps = b; if (int.TryParse(Value(RateBox), out var r)) _encoder.SampleRate = r; _encoder.ServerType = Value(ServerBox); _encoder.Host = HostBox.Text; if (int.TryParse(PortBox.Text, out var p)) _encoder.Port = p; _encoder.Mount = MountBox.Text; _encoder.Metadata = MetadataBox.Text; _encoder.StationName = StationNameBox.Text; _encoder.Description = DescriptionBox.Text; _encoder.StationUrl = StationUrlBox.Text; _encoder.Genre = GenreBox.Text; _encoder.Aim = AimBox.Text; _encoder.Irc = IrcBox.Text; _encoder.Icq = IcqBox.Text; EncoderGrid.Items.Refresh(); }
    private void Password_Changed(object sender, RoutedEventArgs e) { if (!_loading && _encoder is not null) _encoder.Password = PasswordBox.Password; }
    private void Enabled_Changed(object sender, RoutedEventArgs e) { if (!_loading && _encoder is not null) { _encoder.Enabled = EnabledBox.IsChecked == true; EncoderGrid.Items.Refresh(); } }
    private void AddInstance_Click(object sender, RoutedEventArgs e) { if (_instances.Count >= MaxInstances) { MessageBox.Show("Limite di 64 istanze raggiunto."); return; } var x = NewInstance(_instances.Count + 1); _instances.Add(x); InstanceList.SelectedItem = x; }
    private void DuplicateInstance_Click(object sender, RoutedEventArgs e) { if (_instance is null || _instances.Count >= MaxInstances) return; var x = new SourceInstance { Name = _instance.Name + " copia", SourceType = _instance.SourceType, Source = _instance.Source, InputSampleRate = _instance.InputSampleRate, Encoders = _instance.Encoders.Select(CloneEncoder).ToList() }; _instances.Add(x); InstanceList.SelectedItem = x; }
    private void RemoveInstance_Click(object sender, RoutedEventArgs e) { if (_instance is null) return; foreach (var x in _instance.Encoders) x.IsRunning = false; _instances.Remove(_instance); InstanceList.SelectedIndex = _instances.Count > 0 ? 0 : -1; RefreshFooter(); }
    private void AddEncoder_Click(object sender, RoutedEventArgs e) { if (_instance is null) return; var x = new EncoderProfile { Name = $"Stream {_instance.Encoders.Count + 1}" }; _instance.Encoders.Add(x); EncoderGrid.Items.Refresh(); EncoderGrid.SelectedItem = x; RefreshFooter(); }
    private void DuplicateEncoder_Click(object sender, RoutedEventArgs e) { if (_instance is null || _encoder is null) return; var x = CloneEncoder(_encoder); x.Name += " copia"; _instance.Encoders.Add(x); EncoderGrid.Items.Refresh(); EncoderGrid.SelectedItem = x; RefreshFooter(); }
    private void RemoveEncoder_Click(object sender, RoutedEventArgs e) { if (_instance is null || _encoder is null) return; _encoder.IsRunning = false; _instance.Encoders.Remove(_encoder); EncoderGrid.Items.Refresh(); EncoderGrid.SelectedIndex = _instance.Encoders.Count > 0 ? 0 : -1; RefreshFooter(); }
    private async void Save_Click(object sender, RoutedEventArgs e) { await _store.SaveAsync(_instances); }
    private async void Export_Click(object sender, RoutedEventArgs e) { var dialog = new SaveFileDialog { Title = "Esporta configurazione completa", Filter = "Configurazione StreamPAL (*.streampal)|*.streampal", FileName = $"StreamPAL-backup-{DateTime.Now:yyyy-MM-dd}.streampal", AddExtension = true }; if (dialog.ShowDialog() != true) return; await _store.ExportAsync(dialog.FileName, _instances); MessageBox.Show("Configurazione esportata. Il file contiene anche le password: conservalo in un luogo sicuro.", "StreamPAL"); }
    private async void Import_Click(object sender, RoutedEventArgs e) { var dialog = new OpenFileDialog { Title = "Importa configurazione", Filter = "Configurazione StreamPAL (*.streampal)|*.streampal|File JSON (*.json)|*.json" }; if (dialog.ShowDialog() != true) return; try { var imported = await _store.ImportAsync(dialog.FileName); if (imported.Count > MaxInstances) { MessageBox.Show("Il file contiene più di 64 istanze."); return; } _instances.Clear(); foreach (var x in imported) _instances.Add(x); InstanceList.SelectedIndex = _instances.Count > 0 ? 0 : -1; await _store.SaveAsync(_instances); RefreshFooter(); MessageBox.Show("Configurazione importata correttamente.", "StreamPAL"); } catch (Exception ex) { MessageBox.Show($"Impossibile importare il file: {ex.Message}", "StreamPAL"); } }
    private void ExportAllStatistics_Click(object sender, RoutedEventArgs e) { var dialog = new SaveFileDialog { Title = "Esporta statistiche", Filter = "Cartella di lavoro Excel (*.xlsx)|*.xlsx", FileName = $"StreamPAL-statistiche-{DateTime.Now:yyyy-MM-dd}.xlsx", AddExtension = true }; if (dialog.ShowDialog() != true) return; var basePath = Path.Combine(Path.GetDirectoryName(dialog.FileName)!, Path.GetFileNameWithoutExtension(dialog.FileName)); var exportable = _instances.Where(x => StatisticsService.Instance.Get(x).Count > 0).ToList(); if (exportable.Count == 0) { MessageBox.Show("Non sono ancora disponibili campioni statistici.", "StreamPAL"); return; } foreach (var (instance, index) in exportable.Select((x,i)=>(x,i))) { var path = exportable.Count == 1 ? dialog.FileName : $"{basePath}-{SafeName(instance.Name)}.xlsx"; StatisticsExcelExporter.Export(path, instance, StatisticsService.Instance.Get(instance)); } MessageBox.Show(exportable.Count == 1 ? "Statistiche esportate." : $"Esportati {exportable.Count} file Excel, uno per istanza.", "StreamPAL"); }
    private void StartWithWindows_Click(object sender, RoutedEventArgs e) { _settings.StartWithWindows = StartWithWindowsMenu.IsChecked; if (_settings.StartWithWindows) { _settings.StartAllWithWindows = false; StartAllWithWindowsMenu.IsChecked = false; } _settingsService.Save(_settings); }
    private void StartAllWithWindows_Click(object sender, RoutedEventArgs e) { _settings.StartAllWithWindows = StartAllWithWindowsMenu.IsChecked; if (_settings.StartAllWithWindows) { _settings.StartWithWindows = false; StartWithWindowsMenu.IsChecked = false; } _settingsService.Save(_settings); }
    private void Language_Click(object sender, RoutedEventArgs e) { if ((sender as FrameworkElement)?.Tag is not string language) return; _settings.Language = language; _settingsService.Save(_settings); MessageBox.Show("La lingua sarà applicata completamente al prossimo avvio.", "StreamPAL"); LocalizationService.Apply(this, language); }
    private void Exit_Click(object sender, RoutedEventArgs e) => Close();
    private void Statistics_Click(object sender, RoutedEventArgs e) { if ((sender as FrameworkElement)?.Tag is SourceInstance instance) new StatisticsWindow(instance) { Owner = this }.Show(); }
    private void Info_Click(object sender, RoutedEventArgs e) { try { new InfoWindow { Owner = this }.ShowDialog(); } catch (Exception ex) { MessageBox.Show($"Impossibile aprire la finestra Info: {ex.Message}", "StreamPAL", MessageBoxButton.OK, MessageBoxImage.Error); } }
    private void Registration_Click(object sender, RoutedEventArgs e) => ShowRegistration(true);
    private async void StressTest_Click(object sender, RoutedEventArgs e) { try { IsEnabled = false; System.Windows.Input.Mouse.OverrideCursor = System.Windows.Input.Cursors.Wait; var result = await StressTestService.RunAsync(); MessageBox.Show($"Test completato correttamente.\n\n{result.Instances} istanze · {result.Encoders} encoder\n{result.PcmBytesProcessed / 1024d / 1024d:N1} MiB audio elaborati\nTempo: {result.Elapsed.TotalSeconds:N1} s\nMemoria residua: {result.MemoryDelta / 1024d / 1024d:N1} MiB", "StreamPAL · Test di stabilità", MessageBoxButton.OK, MessageBoxImage.Information); } catch (Exception ex) { MessageBox.Show($"Test non superato: {ex.Message}", "StreamPAL", MessageBoxButton.OK, MessageBoxImage.Error); } finally { System.Windows.Input.Mouse.OverrideCursor = null; IsEnabled = true; } }
    private void Start_Click(object sender, RoutedEventArgs e) { if (_encoder is null || _instance is null) return; var encoder = _encoder; var instance = _instance; var starting = !encoder.IsRunning; if (starting && _trial.IsExpired) { ShowRegistration(true); return; } if (starting) { encoder.ClearLog(); encoder.AddLog($"Preparazione {encoder.Codec} {encoder.BitrateKbps} kbps / {encoder.SampleRate} Hz"); if (!instance.Encoders.Any(x => x.IsRunning)) { try { encoder.AddLog($"Apertura sorgente {instance.SourceType}: {instance.Source}"); _audioMeters.Start(instance); encoder.AddLog($"Sorgente aperta a {instance.InputSampleRate / 1000d:0.0} kHz"); } catch (Exception ex) { encoder.AddLog($"ERRORE sorgente: {ex.Message}"); MessageBox.Show($"Impossibile aprire la sorgente audio: {ex.Message}", "StreamPAL", MessageBoxButton.OK, MessageBoxImage.Error); return; } } encoder.AddLog("Attesa campioni audio per avviare l'handshake…"); } encoder.IsRunning = starting; encoder.Enabled = starting; encoder.IsConnected = false; if (!starting) { _reconnectAfter.TryRemove(encoder.Id, out _); if (_broadcastSessions.TryRemove(encoder.Id, out var session)) session.Dispose(); encoder.AddLog("Streaming arrestato"); encoder.Listeners = 0; if (!instance.Encoders.Any(x => x.IsRunning)) { _audioMeters.Stop(instance.Id); instance.LeftLevel = instance.RightLevel = 0; } } if (_instances.SelectMany(x => x.Encoders).Any(x => x.IsRunning)) _meter.Start(); else _meter.Stop(); EncoderGrid.Items.Refresh(); InstanceList.Items.Refresh(); UpdateStatus(); }
    private void UpdateStatus() { if (_encoder is null) return; StartButton.Content = _encoder.IsRunning ? "Ferma" : "Avvia streaming"; }
    private async Task UpdateMetersAsync() { foreach (var instance in _instances) { if (instance.Encoders.Any(x => x.IsRunning)) { var levels = _audioMeters.Read(instance.Id); instance.LeftLevel = levels.Left; instance.RightLevel = levels.Right; } else instance.LeftLevel = instance.RightLevel = 0; instance.RefreshStats(); } if (_instance is not null) { LeftVu.Value = _instance.LeftLevel; RightVu.Value = _instance.RightLevel; VuDbText.Text = $"L {_instance.LeftDb} / R {_instance.RightDb} dB"; } else VuDbText.Text = "−∞ / −∞ dB"; if (!_listenerPollRunning && DateTime.UtcNow >= _nextListenerPoll) { _listenerPollRunning = true; _nextListenerPoll = DateTime.UtcNow.AddSeconds(5); try { foreach (var encoder in _instances.SelectMany(x => x.Encoders).Where(x => x.IsRunning && x.IsConnected)) { try { encoder.Listeners = await _listenerMonitor.ReadAsync(encoder); } catch { encoder.Listeners = 0; } var metadata = encoder.Metadata ?? ""; if (_sentMetadata.GetValueOrDefault(encoder.Id) != metadata) { try { await _metadataUpdater.UpdateAsync(encoder); _sentMetadata[encoder.Id] = metadata; encoder.AddLog("Metadata aggiornati"); } catch (Exception ex) { if (!encoder.ConnectionLog.Contains("Metadata non aggiornati")) encoder.AddLog($"Metadata non aggiornati: {ex.Message}"); } } } foreach (var x in _instances) x.RefreshStats(); InstanceList.Items.Refresh(); EncoderGrid.Items.Refresh(); } finally { _listenerPollRunning = false; } } if (DateTime.UtcNow >= _nextStatisticsSample) { _nextStatisticsSample = DateTime.UtcNow.AddMinutes(1); foreach (var instance in _instances.Where(x => x.Encoders.Any(e => e.Enabled || e.IsRunning))) await StatisticsService.Instance.RecordAsync(instance); } }
    private void RefreshFooter() { var count = _instances.Sum(x => x.Encoders.Count); Footer.Text = $"{_instances.Count} / {MaxInstances} istanze · {count} encoder totali"; }
    private static string SafeName(string name) => string.Concat(name.Select(c => Path.GetInvalidFileNameChars().Contains(c) ? '_' : c));
    private static EncoderProfile CloneEncoder(EncoderProfile x) => new() { Name = x.Name, ChannelMode = x.ChannelMode, OutputMode = x.OutputMode, Codec = x.Codec, BitrateKbps = x.BitrateKbps, SampleRate = x.SampleRate, ServerType = x.ServerType, Host = x.Host, Port = x.Port, Mount = x.Mount, Username = x.Username, Password = x.Password, Metadata = x.Metadata, StationName = x.StationName, Description = x.Description, StationUrl = x.StationUrl, Genre = x.Genre, Aim = x.Aim, Irc = x.Irc, Icq = x.Icq, Enabled = x.Enabled };
    protected override void OnInitialized(EventArgs e) { base.OnInitialized(e); _audioMeters.PcmAvailable += OnPcmAvailable; }
    private void OnPcmAvailable(Guid instanceId, byte[] data, NAudio.Wave.WaveFormat format)
    {
        var instance = _instances.FirstOrDefault(x => x.Id == instanceId); if (instance is null) return;
        foreach (var encoder in instance.Encoders.Where(x => x.IsRunning))
        {
            if (_broadcastSessions.TryGetValue(encoder.Id, out var existing) && existing.IsCompleted)
            {
                if (_broadcastSessions.TryRemove(encoder.Id, out var ended)) ended.Dispose();
                _reconnectAfter[encoder.Id] = DateTime.UtcNow.AddSeconds(5); encoder.IsConnected = false; encoder.AddLog("Connessione interrotta. Nuovo tentativo tra 5 secondi…");
            }
            if (_reconnectAfter.TryGetValue(encoder.Id, out var retryAt) && DateTime.UtcNow < retryAt) continue;
            _reconnectAfter.TryRemove(encoder.Id, out _);
            var session = _broadcastSessions.GetOrAdd(encoder.Id, _ => encoder.Codec switch { "AAC-LC" => new AacBroadcastSession(encoder, format, false), "AAC+ (HE-AAC)" => new AacBroadcastSession(encoder, format, true), "Opus" => new OpusBroadcastSession(encoder, format), "OGG Vorbis" => new OggBroadcastSession(encoder, format), _ => new Mp3BroadcastSession(encoder, format) }); session.Feed(data);
        }
    }
    private void CheckTrial() { if (!TrialLicenseService.IsTrialBuild || _trial.IsRegistered) return; _trial.Checkpoint(); RefreshTrialUi(); if (_trial.IsExpired) { StopAllForTrial(); if (!_expiryPromptShown) { _expiryPromptShown = true; ShowRegistration(true); } } }
    private void RefreshTrialUi() { if (!TrialLicenseService.IsTrialBuild) return; TrialHeader.Visibility = _trial.IsRegistered ? Visibility.Collapsed : Visibility.Visible; RegistrationMenu.Header = _trial.IsRegistered ? "Registration ✓" : "Registration"; VersionHeader.Text = _trial.IsRegistered ? "Versione 1.0.0 · Registrato" : $"Versione 1.0.0 · Prova rimanente {_trial.Remaining:hh\\:mm\\:ss}"; Title = _trial.IsRegistered ? "StreamPAL" : "StreamPAL · TRIAL VERSION"; }
    private void ShowRegistration(bool force = false) { if (!TrialLicenseService.IsTrialBuild || _registrationOpen) return; if (!force && _expiryPromptShown && _trial.IsExpired) return; _registrationOpen = true; try { var window = new RegistrationWindow(_trial, _settings.Language) { Owner = this }; window.ShowDialog(); if (_trial.IsRegistered) _expiryPromptShown = false; RefreshTrialUi(); } finally { _registrationOpen = false; } }
    private void StopAllForTrial() { _meter.Stop(); foreach (var session in _broadcastSessions.Values) session.Dispose(); _broadcastSessions.Clear(); foreach (var instance in _instances) { _audioMeters.Stop(instance.Id); instance.LeftLevel = instance.RightLevel = 0; foreach (var encoder in instance.Encoders) { encoder.IsRunning = encoder.Enabled = encoder.IsConnected = false; encoder.Listeners = 0; } } EncoderGrid.Items.Refresh(); InstanceList.Items.Refresh(); }
    protected override void OnClosed(EventArgs e) { _trialTimer.Stop(); _trial.Dispose(); _meter.Stop(); foreach (var session in _broadcastSessions.Values) session.Dispose(); _broadcastSessions.Clear(); _audioMeters.Dispose(); base.OnClosed(e); }
}
