using System.IO; using System.Net.Sockets; using System.Text; using NAudio.Wave; using NAudio.Wave.SampleProviders; using StreamForge.Models;
namespace StreamForge.Services;
public sealed class AacBroadcastSession : IBroadcastSession
{
    private readonly EncoderProfile _encoder; private readonly bool _he; private readonly BufferedWaveProvider _buffer; private readonly CancellationTokenSource _stop=new(); private readonly Task _worker;
    public AacBroadcastSession(EncoderProfile encoder,WaveFormat format,bool highEfficiency){_encoder=encoder;_he=highEfficiency;_buffer=new BufferedWaveProvider(format){BufferDuration=TimeSpan.FromSeconds(2),DiscardOnBufferOverflow=true,ReadFully=false};_worker=Task.Run(RunAsync);}
    public bool IsCompleted=>_worker.IsCompleted;
    public void Feed(byte[] data){if(!_stop.IsCancellationRequested)_buffer.AddSamples(data,0,data.Length);}
    private async Task RunAsync(){try{_encoder.AddLog("Connessione al server sorgente…");using var tcp=new TcpClient();await tcp.ConnectAsync(_encoder.Host,_encoder.Port,_stop.Token);using var network=tcp.GetStream();await HandshakeAsync(network,_stop.Token);_buffer.ClearBuffer();var routed=new RoutingSampleProvider(_buffer.ToSampleProvider(),_encoder.ChannelMode);var resampled=new WdlResamplingSampleProvider(routed,_encoder.SampleRate);var pcm=new SampleToWaveProvider16(resampled);using var aac=new FdkAacEncoder(_encoder.SampleRate,pcm.WaveFormat.Channels,_encoder.BitrateKbps*1000,_he);_encoder.IsConnected=true;_encoder.AddLog($"Handshake accettato: streaming {(_he?"AAC+":"AAC-LC")} attivo");var samples=new short[aac.InputSamplesPerFrame];var bytes=new byte[samples.Length*2];var filled=0;while(!_stop.IsCancellationRequested){var read=pcm.Read(bytes,filled*2,bytes.Length-filled*2);if(read==0){await Task.Delay(5,_stop.Token);continue;}filled+=read/2;if(filled<samples.Length)continue;Buffer.BlockCopy(bytes,0,samples,0,bytes.Length);var encoded=aac.Encode(samples);if(encoded.Length>0){await network.WriteAsync(encoded,_stop.Token);await network.FlushAsync(_stop.Token);}filled=0;}}catch(OperationCanceledException){}catch(Exception ex){_encoder.AddLog($"ERRORE streaming AAC: {ex.Message}");}finally{_encoder.IsConnected=false;}}
    private async Task HandshakeAsync(NetworkStream stream,CancellationToken token){var content=_he?"audio/aacp":"audio/aac";string request;if(_encoder.ServerType=="Icecast 2"){var mount=_encoder.Mount.StartsWith('/')?_encoder.Mount:"/"+_encoder.Mount;var auth=Convert.ToBase64String(Encoding.UTF8.GetBytes($"source:{_encoder.Password}"));request=$"PUT {mount} HTTP/1.1\r\nHost: {_encoder.Host}:{_encoder.Port}\r\nAuthorization: Basic {auth}\r\nUser-Agent: StreamPAL/1.0.0\r\nContent-Type: {content}\r\nIce-Name: {_encoder.StationName}\r\nIce-Public: 0\r\n\r\n";}else request=$"{_encoder.Password}\r\nicy-name:{_encoder.StationName}\r\nicy-pub:0\r\nicy-br:{_encoder.BitrateKbps}\r\ncontent-type:{content}\r\n\r\n";await stream.WriteAsync(Encoding.UTF8.GetBytes(request),token);await stream.FlushAsync(token);var response=new byte[1024];using var timeout=CancellationTokenSource.CreateLinkedTokenSource(token);timeout.CancelAfter(TimeSpan.FromSeconds(8));var read=await stream.ReadAsync(response,timeout.Token);var text=Encoding.ASCII.GetString(response,0,read);_encoder.AddLog("Server: "+text.Split('\r','\n',StringSplitOptions.RemoveEmptyEntries).FirstOrDefault());if(!(text.Contains("200")||text.Contains("OK2")||text.StartsWith("OK")))throw new IOException("Autenticazione rifiutata: "+text.Trim());}
    public void Dispose(){_stop.Cancel();try{_worker.Wait(2000);}catch{} _stop.Dispose();}
}
